### ISSUE TITLE
map_twix: index 1182720 is out of bounds for axis 0 with size 1182720

### ISSUE THREAD

**Issue by ZhengguoTan** [pehses/twixtools#10]
Dear twixtools developers,

Thank you first of all for providing such an excellent tool! I enjoy it very much and use it.

Recently I try to use the map_twix function to map a .dat file with the shape:

(1, 1, 1, 1, 1, 2, 1, 32, 1, 1, 1, 84, 1, 220, 32, 220)

However, an error occurs in https://github.com/pehses/twixtools/blob/master/twixtools/map_twix.py#L645

which throws an IndexError:

index 1182720 is out of bounds for axis 0 with size 1182720.

My questions may be:

1) Is such data too large for map_twix? Or does the data itself contains some error?
2) Is there some way to debug such as to understand why this error occurs?

Best Regards,
Zhengguo Tan

**Comment by pehses** [comment]
Dear Zhengguo

difficult to say whether this is a bug in twixtools or a broken file.

The data is certainly not too large for map_twix. The error occurs during sorting of one of the data blocks into the output array. The data blocks are always 2D (channels x columns). The output array is at this point 3D and will be reshaped later into the target size. What is happening now is that the calculated index position (1182720) is out of bounds of the predetermined size of this "3rd dimension".  Most likely, there is a problem reading the line counters correctly (counters for phase-encoding line, partition, slice, repetition, ...), so that the index (which is calculated from these counters) is wrong.

If you want, I can have a look at the data to find out what is happening.

Philipp
