### ISSUE TITLE
Multi-echo EPI echo index issue in twix from XA system

### ISSUE THREAD

**Issue by wenshangwang** [pehses/twixtools#29]
Dear Philipp

As the Siemens system updated to XA, the SBB source code for EPI readout is not available to customer and all the echo counter from Mdh will always be 0. This has caused me not able to map the correct kspace matrix for multi-echo EPI scans using twixtools. 

I am curious if you will update the code to make it accommodate this change from Siemens. Our site has no longer have scanner that still use VE's system. I have found those tools like regrid are super helpful and convenient for my multi-echo EPI reconstruction when using VE's data.  

Best
Wenshang

**Comment by pehses** [comment]
Dear Wenshang,

twixtools will make use of all counters that were set during the scan, so in principle such a change should not require any modifications of twixtools (that is as long as the underlying file format did not change, and this does not seem to be the case). 
Can you find out which Mdh counters are used by Siemens' new EPI readout? This should be easy to find out by reading the data in with twix_tools.read_twix(filename), and then looking at the individual mdb's (e.g. print(twix[-1]['mdb'][23])

Best,
Philipp

**Comment by wenshangwang** [comment]
Thanks for your reply Philipp

Here is the mdb printout for one of the line, which should already be the imaging data. Variable mdb is defined as mdb = TWIX[-1]['mdb'][100]. 

![image](https://github.com/user-attachments/assets/fac13d6c-ea49-44fe-b69b-7cd9a933a4b2)
The echo counter is not shown in there.

Here is the dimension of my image data when I used twixtools.map_twix. epi = TWIX[-1]['image'] with Seg average turned off. 
![image](https://github.com/user-attachments/assets/7481fdc4-cd8c-4609-983a-28661ed3b1d1)
I am a bit not sure what each dimension represent  but the correct 3 echos dimension is not included in there. 

Thanks
Wenshang

**Comment by pehses** [comment]
Hi Wenshang,

the Eco (and Phs) counters were indeed missing from the print(mdb) function, I just fixed that and pushed it to the main branch. However, this is really just a cosmetic change, you can always get the counter by accessing it like so:
print(TWIX[-1]['mdb'][100].mdh.Counter.Eco)

So, I would still first check whether the Eco counter - or some equivalent counter -  is set (i.e. that the counter is sometimes larger than 0) in the mdb, since that's as low-level as it gets. After verifying that there is indeed a counter for the eco dimensions, you can then proceed and look at the map_twix/twix_array object.

Regarding the twix_array object ('epi' in your case): this object also has a .shape property of its own, so you don't need to first convert it to numpy with the [:]. Furthermore, there's a .size property that takes the dimension name as an input (epi.size['Eco']), and then there's also the .dims property that tells you the order of the dimensions (so you can make sense of the .shape output).

You can also just simply 'print(epi)' to get a lot of additional information.

Philipp

**Comment by wenshangwang** [comment]
Hi Philipp

There is an eco counter there but it remains zero(zero-based) for the whole EPI scan. I am guessing this is the problem that kept the twixtools from mapping multi-echo EPI correctly. 

This might not be a easy fix for the tool I guess as this is more sequence related issues. 

Wenshang

**Comment by pehses** [comment]
Hi Wenshang,

yes, this appears to be sequence-related. twixtools will just use the information from the file, so if the counter is not set then there will be no eco dimension in the mapped array object. You could manually set this eco counter in the twix-object and then use map_twix(twix), but it would be better to just fix the sequence, or find out how the eco dimension is identified by the ICE program.

I'm closing this since it does not appear to be an issue of twixtools.

Best,
Philipp
