### ISSUE TITLE
Loading and saving dat file causes Siemens' reconstruction to fail

### ISSUE THREAD

**Issue by Michael-Tanzer** [pehses/twixtools#5]
Hi,

I have encountered the following issue: whenever a .dat file is opened, saved to a different file and then reconstructed with Siemens' software, the reconstruct fails (find error message below)

Steps to reproduce:
---

```
multi_twix = twixtools.read_twix(original_file_path)
twixtools.write_twix(multi_twix, output_file_path)
```
Then try to reconstruct with Siemens' reconstruction

Error message (or what I think is the relevant bit):
---
```
      13        2021/06/16-15:55:21.814239      Error   DLL     1756    ReadoutChecker  readoutchecker_safety.cpp:187   IReadoutCheckerImpl::CheckScanId        invalid scan Id in scan header
                                                                                                                                  scan 1
                                                                                                                                 : expected scan Id 1
                                                                                                                                  received scan Id 2
      13        2021/06/16-15:55:21.814239      Error   DLL     1756    ReadoutChecker  readoutchecker_safety.cpp:374   IReadoutCheckerImpl::Decompose  mdh check failed
```

**Comment by pehses** [comment]
Can you try this again with the lastest version? The latest commit fixes numerous bugs, and it's quite likely that this problem is fixed now.

The 'test' directory now also contains the file 'test_lossless.py' which reads a file, writes it back, and then compares the md5sum to the original file. All twix files I've tested passed it. You can run this test by running 'python setup.py test' from the project's root directory (note that this will run all tests, some of which will fail if package requirements are not met).

**Comment by Michael-Tanzer** [comment]
Thank you very much. The new release completely solved the bug.
